Repository HY-MealReview/Frontend, pull requests merged in 2024-10, with the labels that each got.

#2 [Feat] 스플래시 구현
  src/App.tsx
  src/assets/common/error.png
  src/assets/common/logo.png
  src/assets/common/splash.png
  src/components/common/Layout.tsx
  src/components/common/Splash.tsx
  src/components/common/TabNavigator.tsx
  src/pages/error/error.tsx
Labels: ✨ Feature, :large_blue_circle: 예안

#5 [Feat] 설정 페이지 UI 구현
  src/assets/setting/prev-arrow.svg
  src/assets/setting/right-arrow.svg
  src/pages/setting/setting.tsx
  tailwind.config.ts
Labels: ✨ Feature, :large_blue_circle: 예안

#6 [Feat] 로그인 페이지 UI 구현
  src/App.tsx
  src/assets/common/logo.png
  src/assets/common/logo.svg
  src/assets/login/eye_closed.svg
  src/assets/login/eye_open.svg
  src/components/common/Splash.tsx
  src/pages/login/login.tsx
  src/pages/setting/setting.tsx
  src/pages/signup/signup.tsx
Labels: ✨ Feature, :large_blue_circle: 예안

#7 [Feat] 회원가입 UI 구현
  package.json
  src/assets/common/prev-arrow.svg
  src/pages/login/login.tsx
  src/pages/setting/setting.tsx
  src/pages/signup/signup.tsx
  yarn.lock
Labels: ✨ Feature, :large_blue_circle: 예안

#10 [Feat] 메인페이지 UI 구현
  package-lock.json
  package.json
  src/assets/main/NoImage.webp
  src/assets/main/Recommend.webp
  src/assets/main/logo.webp
  src/assets/main/menuImage.webp
  src/pages/main/main-types.tsx
  src/pages/main/main.tsx
  yarn.lock
Labels: ✨ Feature

#12 [Setting] Netlify 새로고침 리다이렉트 설정
  public/_redirects
  src/pages/signup/signup.tsx
Labels: 🔧 Configuration, :large_blue_circle: 예안

#14 [Feat] 회원가입 로직 구현
  package.json
  src/components/signup/NicknameStep.tsx
  src/components/signup/PasswordStep.tsx
  src/components/signup/SignUpLayout.tsx
  src/components/signup/StudentIdStep.tsx
  src/pages/login/login.tsx
  src/pages/signup/signup.tsx
  src/store/signupStore.ts
  yarn.lock
Labels: ✨ Feature, :large_blue_circle: 예안
